/*
 * This code has been generated by the Rebel: a code generator for modern Java.
 *
 * Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
 */
package org.pu.fmi.requirement.engineering.model;

import java.time.LocalDateTime;
import java.util.HashSet;
import java.util.Objects;
import java.util.Set;


public class MovieProjection {
    private String title;
    private LocalDateTime startTime;
    private Room room;
    private Set<Reservation> reservations;

    public MovieProjection() {
        this.reservations = new HashSet<>();
    }

    public String getTitle() {
        return title;
    }

    public LocalDateTime getStartTime() {
        return startTime;
    }

    public Room getRoom() {
        return room;
    }

    public Set<Reservation> getReservations() {
        return reservations;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public void setStartTime(LocalDateTime startTime) {
        this.startTime = startTime;
    }

    public void setRoom(Room room) {
        this.room = room;
    }

    public void setReservations(Set<Reservation> reservations) {
        this.reservations = reservations;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        MovieProjection that = (MovieProjection) o;
        return Objects.equals(title, that.title) && Objects.equals(startTime, that.startTime) && Objects.equals(room, that.room) && Objects.equals(reservations, that.reservations);
    }

    @Override
    public int hashCode() {
        return Objects.hash(title, startTime, room, reservations);
    }
}