/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package org.pu.fmi.requirement.engineering.model;

import java.util.Objects;

public class Reservation {
    private Seat seat;

    public Reservation(Seat seat, User user) {
        this.seat = seat;
        this.user = user;
    }

    private User user;

    public Seat getSeat() {
        return seat;
    }

    public User getUser() {
        return user;
    }

    public void setSeat(Seat seat) {
        this.seat = seat;
    }

    public void setUser(User user) {
        this.user = user;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Reservation that = (Reservation) o;
        return Objects.equals(seat, that.seat) && Objects.equals(user, that.user);
    }

    @Override
    public int hashCode() {
        return Objects.hash(seat, user);
    }
}