/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package org.pu.fmi.requirement.engineering.model;

import java.util.HashSet;
import java.util.Set;



public class Room {
    private Set<Seat> seats;

    public Room() {
        this.seats = new HashSet<>();
    }

    public Set<Seat> getSeats() {
        return seats;
    }

    public void setSeats(Set<Seat> seats) {
        this.seats = seats;
    }
}